import { RestaurantDatabase } from '../src/types';

export const initialDatabase: RestaurantDatabase = {
  settings: {
    restaurantNameAr: 'مطعم بيتنا الشامي',
    restaurantNameEn: 'Baitna Al-Shami Restaurant',
    logoUrl: '/icon.svg',
    phone: '+963 11 332 9400',
    addressAr: 'دمشق القديمة - باب توما - زقاق الياسمين',
    addressEn: 'Old Damascus - Bab Touma - Jasmine Alley',
    currency: 'SYP',
    currencySymbol: 'ل.س',
    taxPercentage: 0,
    enableKitchenSound: true,
    autoPrintOnSubmit: true,
    serverLocalIp: '192.168.1.100',
    serverPort: 3000,
    primaryLanguage: 'ar',
  },
  nextOrderNumber: 1048,
  users: [
    {
      id: 'usr-admin',
      username: 'admin',
      name: 'المدير العام (أبو سليم)',
      pin: '1111',
      role: 'ADMIN',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-mgr',
      username: 'manager',
      name: 'مدير الصالة (وسيم)',
      pin: '2222',
      role: 'MANAGER',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-w1',
      username: 'waiter01',
      name: 'أحمد الشامي',
      pin: '1234',
      role: 'WAITER',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-w2',
      username: 'waiter02',
      name: 'عمر الحلبي',
      pin: '5678',
      role: 'WAITER',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-kitch',
      username: 'kitchen',
      name: 'شيف المطبخ (أبو عبدو)',
      pin: '3333',
      role: 'KITCHEN',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-cashier',
      username: 'cashier',
      name: 'سامي الصندوق',
      pin: '4444',
      role: 'CASHIER',
      active: true,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
  ],
  kitchenStations: [
    {
      id: 'st-grill',
      code: 'GRILL',
      nameAr: 'قسم المشاوي والفحم',
      nameEn: 'Grill & Charcoal Station',
      icon: 'Flame',
      sortOrder: 1,
    },
    {
      id: 'st-hot',
      code: 'HOT_FOOD',
      nameAr: 'المطبخ الساخن والفتات',
      nameEn: 'Hot Kitchen & Fatteh',
      icon: 'Soup',
      sortOrder: 2,
    },
    {
      id: 'st-appetizers',
      code: 'APPETIZERS',
      nameAr: 'المقبلات والسلطات',
      nameEn: 'Cold Mezze & Salads',
      icon: 'Salad',
      sortOrder: 3,
    },
    {
      id: 'st-drinks',
      code: 'DRINKS',
      nameAr: 'بار المشروبات والعصائر',
      nameEn: 'Drinks & Juice Bar',
      icon: 'Coffee',
      sortOrder: 4,
    },
    {
      id: 'st-desserts',
      code: 'DESSERTS',
      nameAr: 'الحلويات الشرقية',
      nameEn: 'Oriental Sweets',
      icon: 'Cake',
      sortOrder: 5,
    },
  ],
  tables: [
    {
      id: 'tbl-1',
      number: 1,
      nameAr: 'طاولة البحرة 1',
      nameEn: 'Fountain Table 1',
      seats: 4,
      zone: 'أرض الديار (Damascus Courtyard)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-2',
      number: 2,
      nameAr: 'طاولة البحرة 2',
      nameEn: 'Fountain Table 2',
      seats: 6,
      zone: 'أرض الديار (Damascus Courtyard)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-3',
      number: 3,
      nameAr: 'طاولة الياسمين 3',
      nameEn: 'Jasmine Table 3',
      seats: 8,
      zone: 'أرض الديار (Damascus Courtyard)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-4',
      number: 4,
      nameAr: 'طاولة الشرفة 4',
      nameEn: 'Courtyard Nook 4',
      seats: 4,
      zone: 'أرض الديار (Damascus Courtyard)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-5',
      number: 5,
      nameAr: 'الصالة الرئيسية 5',
      nameEn: 'Main Hall 5',
      seats: 4,
      zone: 'الصالة الرئيسية (Main Hall)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-6',
      number: 6,
      nameAr: 'الصالة الرئيسية 6',
      nameEn: 'Main Hall 6',
      seats: 6,
      zone: 'الصالة الرئيسية (Main Hall)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-7',
      number: 7,
      nameAr: 'الصالة الرئيسية 7',
      nameEn: 'Main Hall 7',
      seats: 2,
      zone: 'الصالة الرئيسية (Main Hall)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-8',
      number: 8,
      nameAr: 'الصالة الرئيسية 8',
      nameEn: 'Main Hall 8',
      seats: 6,
      zone: 'الصالة الرئيسية (Main Hall)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-9',
      number: 9,
      nameAr: 'الصالة الرئيسية 9',
      nameEn: 'Main Hall 9',
      seats: 4,
      zone: 'الصالة الرئيسية (Main Hall)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-10',
      number: 10,
      nameAr: 'صالة العائلات 10',
      nameEn: 'Family Hall 10',
      seats: 8,
      zone: 'صالة العائلات (Family Lounge)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-11',
      number: 11,
      nameAr: 'صالة العائلات 11',
      nameEn: 'Family Hall 11',
      seats: 10,
      zone: 'صالة العائلات (Family Lounge)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
    {
      id: 'tbl-12',
      number: 12,
      nameAr: 'طاولة التراس 12',
      nameEn: 'Terrace Table 12',
      seats: 4,
      zone: 'التراس الخارجي (Terrace)',
      status: 'AVAILABLE',
      orderAmount: 0,
      updatedAt: '2026-09-22T08:00:00.000Z',
    },
  ],
  categories: [
    {
      id: 'cat-mezze-cold',
      nameAr: 'مقبلات باردة',
      nameEn: 'Cold Mezze',
      icon: 'Utensils',
      sortOrder: 1,
      stationId: 'st-appetizers',
    },
    {
      id: 'cat-mezze-hot',
      nameAr: 'مقبلات ساخنة',
      nameEn: 'Hot Mezze',
      icon: 'Flame',
      sortOrder: 2,
      stationId: 'st-hot',
    },
    {
      id: 'cat-grills',
      nameAr: 'مشاوي شامية وحلبية',
      nameEn: 'Grills & Kebabs',
      icon: 'Beef',
      sortOrder: 3,
      stationId: 'st-grill',
    },
    {
      id: 'cat-mains',
      nameAr: 'وجبات وطبخ شامي',
      nameEn: 'Main Dishes & Stews',
      icon: 'CookingPot',
      sortOrder: 4,
      stationId: 'st-hot',
    },
    {
      id: 'cat-fatteh',
      nameAr: 'فتات شامية',
      nameEn: 'Damascene Fatteh',
      icon: 'Soup',
      sortOrder: 5,
      stationId: 'st-hot',
    },
    {
      id: 'cat-salads',
      nameAr: 'سلطات',
      nameEn: 'Salads',
      icon: 'Salad',
      sortOrder: 6,
      stationId: 'st-appetizers',
    },
    {
      id: 'cat-shawarma',
      nameAr: 'شاورما وسندويش',
      nameEn: 'Shawarma & Sandwiches',
      icon: 'Sandwich',
      sortOrder: 7,
      stationId: 'st-grill',
    },
    {
      id: 'cat-sweets',
      nameAr: 'حلويات شرقية',
      nameEn: 'Desserts & Sweets',
      icon: 'Cake',
      sortOrder: 8,
      stationId: 'st-desserts',
    },
    {
      id: 'cat-cold-drinks',
      nameAr: 'عصائر ومشروبات باردة',
      nameEn: 'Cold Beverages & Juices',
      icon: 'CupSoda',
      sortOrder: 9,
      stationId: 'st-drinks',
    },
    {
      id: 'cat-hot-drinks',
      nameAr: 'مشروبات ساخنة',
      nameEn: 'Hot Drinks',
      icon: 'Coffee',
      sortOrder: 10,
      stationId: 'st-drinks',
    },
  ],
  products: [
    {
      id: 'prd-shish-tawook',
      nameAr: 'شيش طاووق سوري',
      nameEn: 'Syrian Shish Tawook',
      descriptionAr: 'أسياخ دجاج طازجة متبلة بالثوم وعصير الليمون والبهارات الشامية مع ثومية وبطاطا مقلية',
      descriptionEn: 'Charcoal grilled marinated chicken skewers served with authentic garlic cream and fries',
      price: 68000,
      categoryId: 'cat-grills',
      stationId: 'st-grill',
      prepTimeMinutes: 18,
      isAvailable: true,
      sku: 'GRL-101',
      modifiers: [
        {
          id: 'mod-spice',
          nameAr: 'درجة الحرارة',
          nameEn: 'Spice Level',
          required: false,
          multiSelect: false,
          options: [
            { id: 'opt-normal', nameAr: 'عادي', nameEn: 'Mild / Normal', priceDelta: 0 },
            { id: 'opt-spicy', nameAr: 'حار شامي', nameEn: 'Spicy', priceDelta: 0 },
          ],
        },
        {
          id: 'mod-custom',
          nameAr: 'خيارات التجهيز',
          nameEn: 'Preparation Options',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-no-onion', nameAr: 'بدون بصل', nameEn: 'No Onion', priceDelta: 0 },
            { id: 'opt-no-garlic', nameAr: 'بدون ثوم', nameEn: 'No Garlic', priceDelta: 0 },
            { id: 'opt-extra-garlic', nameAr: 'زيادة ثومية', nameEn: 'Extra Garlic Cream', priceDelta: 4000 },
            { id: 'opt-extra-chicken', nameAr: 'سيخ إضافي', nameEn: 'Extra Chicken Skewer', priceDelta: 22000 },
          ],
        },
      ],
    },
    {
      id: 'prd-kebab-halabi',
      nameAr: 'كباب حلبي مشوي على الفحم',
      nameEn: 'Aleppo Charcoal Kebab',
      descriptionAr: 'لحم غنم بلدي مفروم مع الفستق الحلبي والبهارات الحلبية، يقدم مع خضار مشوية وخبز محمر',
      descriptionEn: 'Prime minced lamb with pistachios and Aleppine spices, grilled on charcoal',
      price: 78000,
      categoryId: 'cat-grills',
      stationId: 'st-grill',
      prepTimeMinutes: 15,
      isAvailable: true,
      sku: 'GRL-102',
      modifiers: [
        {
          id: 'mod-kebab-prep',
          nameAr: 'تفضيلات الكباب',
          nameEn: 'Kebab Preferences',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-lean', nameAr: 'بدون دهنة زائدة', nameEn: 'Lean Meat', priceDelta: 0 },
            { id: 'opt-pomegranate', nameAr: 'مع دبس رمان', nameEn: 'Add Pomegranate Glaze', priceDelta: 3000 },
            { id: 'opt-extra-bread', nameAr: 'زيادة خبز بيواز محمر', nameEn: 'Extra Spiced Bread', priceDelta: 2000 },
          ],
        },
      ],
    },
    {
      id: 'prd-mixed-grill',
      nameAr: 'مشاوي مشكلة بيتنا الشامي',
      nameEn: 'Baitna Al-Shami Mixed Grill',
      descriptionAr: 'تشكيلة مميزة: سيخ كباب، سيخ شقف لحم، سيخ شيش طاووق، وعرايس كفتة مع كافة المقبلات المرافقة',
      descriptionEn: 'Generous platter of Kebab, Lamb Chunks, Shish Tawook, and Arayes with grilled veggies',
      price: 125000,
      categoryId: 'cat-grills',
      stationId: 'st-grill',
      prepTimeMinutes: 20,
      isAvailable: true,
      sku: 'GRL-103',
      modifiers: [
        {
          id: 'mod-grill-opt',
          nameAr: 'إضافات المشاوي',
          nameEn: 'Platter Add-ons',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-spicy-dip', nameAr: 'مع محمرة حلبية حارة', nameEn: 'With Spicy Muhammara', priceDelta: 3000 },
            { id: 'opt-extra-chips', nameAr: 'زيادة بطاطا مقلية', nameEn: 'Extra Fries', priceDelta: 5000 },
          ],
        },
      ],
    },
    {
      id: 'prd-hummus',
      nameAr: 'حمص بطحينة شامي',
      nameEn: 'Damascus Hummus with Tahini',
      descriptionAr: 'حمص حب مسلوق ومهروس ناعم مع الطحينة السمسمية والليمون وزيت الزيتون البكر البلدي',
      descriptionEn: 'Smooth chickpea dip blended with pure sesame tahini, lemon juice and virgin olive oil',
      price: 24000,
      categoryId: 'cat-mezze-cold',
      stationId: 'st-appetizers',
      prepTimeMinutes: 5,
      isAvailable: true,
      sku: 'MEZ-201',
      modifiers: [
        {
          id: 'mod-hummus-opt',
          nameAr: 'إضافات الحمص',
          nameEn: 'Hummus Add-ons',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-olive-oil', nameAr: 'زيادة زيت زيتون بلدي', nameEn: 'Extra Virgin Olive Oil', priceDelta: 0 },
            { id: 'opt-meat-pine', nameAr: 'إضافة لحمة مفرومة وصنوبر', nameEn: 'Add Spiced Meat & Pine Nuts', priceDelta: 18000 },
            { id: 'opt-spicy-sauce', nameAr: 'تتبيلة شطة وثوم', nameEn: 'Spicy Chili Garlic Dressing', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-mutabbal',
      nameAr: 'متبل باذنجان حلبي',
      nameEn: 'Aleppo Mutabbal (Charred Eggplant)',
      descriptionAr: 'باذنجان مشوي على الفحم ومهروس مع الطحينة واللبن الزبادي وحبات الرمان البلدي',
      descriptionEn: 'Smoky charcoal-roasted eggplant with tahini, yoghurt, garlic and fresh pomegranate jewels',
      price: 26000,
      categoryId: 'cat-mezze-cold',
      stationId: 'st-appetizers',
      prepTimeMinutes: 5,
      isAvailable: true,
      sku: 'MEZ-202',
      modifiers: [
        {
          id: 'mod-garlic-opt',
          nameAr: 'الثوم والليمون',
          nameEn: 'Garlic & Lemon',
          required: false,
          multiSelect: false,
          options: [
            { id: 'opt-light-garlic', nameAr: 'ثوم خفيف', nameEn: 'Light Garlic', priceDelta: 0 },
            { id: 'opt-extra-garlic', nameAr: 'ثوم زيادة', nameEn: 'Extra Garlic', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-fattoush',
      nameAr: 'فتوش شامي بدبس الرمان',
      nameEn: 'Damascene Fattoush with Pomegranate',
      descriptionAr: 'خضار موسمية طازجة، بقلة، خيار، بندورة، مع رغيف خبز بلدي مقرمش وسماق حلبي ودبس رمان',
      descriptionEn: 'Crisp garden greens, purslane, radishes, crispy pita croutons, sumac and pomegranate dressing',
      price: 25000,
      categoryId: 'cat-salads',
      stationId: 'st-appetizers',
      prepTimeMinutes: 6,
      isAvailable: true,
      sku: 'SLD-301',
      modifiers: [],
    },
    {
      id: 'prd-tabbouleh',
      nameAr: 'تبولة شامية بالنعناع والبرغل',
      nameEn: 'Fresh Syrian Tabbouleh',
      descriptionAr: 'بقدونس مفروم ناعم جداً مع البرغل الأسمر، بندورة، نعناع أخضر وزيت الزيتون الأصلي',
      descriptionEn: 'Finely hand-chopped flat parsley, fine bulgur, ripe tomatoes, mint and fresh lemon oil',
      price: 26000,
      categoryId: 'cat-salads',
      stationId: 'st-appetizers',
      prepTimeMinutes: 6,
      isAvailable: true,
      sku: 'SLD-302',
      modifiers: [],
    },
    {
      id: 'prd-yabraq',
      nameAr: 'يلنجي / ورق عنب بالزيت',
      nameEn: 'Yalanji (Stuffed Vine Leaves)',
      descriptionAr: 'ورق عنب محشي بالأرز والخضار ودبس الرمان والنعناع ومطهو بزيت الزيتون البكر على نار هادئة',
      descriptionEn: 'Tender grape leaves stuffed with spiced rice, tomatoes, herbs and tangy pomegranate syrup',
      price: 32000,
      categoryId: 'cat-mezze-cold',
      stationId: 'st-appetizers',
      prepTimeMinutes: 5,
      isAvailable: true,
      sku: 'MEZ-203',
      modifiers: [],
    },
    {
      id: 'prd-kibbeh-fried',
      nameAr: 'كبة مقلية شامية (4 حبات)',
      nameEn: 'Fried Syrian Kibbeh (4 pcs)',
      descriptionAr: 'أقراص برغل ناعمة محشوة بلحم الغنم البلدي والبصل والصنوبر والمكسرات المحمصة',
      descriptionEn: 'Golden crispy bulgur shells stuffed with spiced minced lamb, onions and roasted pine nuts',
      price: 45000,
      categoryId: 'cat-mezze-hot',
      stationId: 'st-hot',
      prepTimeMinutes: 12,
      isAvailable: true,
      sku: 'MEZ-204',
      modifiers: [],
    },
    {
      id: 'prd-fatteh-hummus',
      nameAr: 'فتة حمص بالسمنة البلدية والصنوبر',
      nameEn: 'Damascus Fatteh with Ghee & Pine Nuts',
      descriptionAr: 'خبز محمص مع حمص حب مسلوق، صوص اللبن بالطحينة والثوم، وتسكب عليها السمنة الحموية الساخنة',
      descriptionEn: 'Layered toasted pita, warm chickpeas, creamy garlic tahini yoghurt, sizzling local samneh & nuts',
      price: 42000,
      categoryId: 'cat-fatteh',
      stationId: 'st-hot',
      prepTimeMinutes: 10,
      isAvailable: true,
      sku: 'FAT-401',
      modifiers: [
        {
          id: 'mod-fatteh-opt',
          nameAr: 'خيارات الفتة',
          nameEn: 'Fatteh Preferences',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-extra-samneh', nameAr: 'سمنة بلدية زيادة', nameEn: 'Extra Browned Ghee', priceDelta: 4000 },
            { id: 'opt-extra-nuts', nameAr: 'زيادة لوز وصنوبر', nameEn: 'Extra Pine Nuts & Almonds', priceDelta: 7000 },
            { id: 'opt-no-garlic', nameAr: 'بدون ثوم', nameEn: 'No Garlic in Yoghurt', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-fatteh-makdous',
      nameAr: 'فتة مكدوس باللحمة الناعمة',
      nameEn: 'Fatteh Makdous with Eggplant & Meat',
      descriptionAr: 'باذنجان صغير محشي باللحمة والصنوبر مع صلصة الطماطم الغنية، خبز مقلي ولبن بالثوم',
      descriptionEn: 'Baby eggplants stuffed with meat and pine nuts, served over toasted bread with tomato reduction',
      price: 54000,
      categoryId: 'cat-fatteh',
      stationId: 'st-hot',
      prepTimeMinutes: 14,
      isAvailable: true,
      sku: 'FAT-402',
      modifiers: [],
    },
    {
      id: 'prd-shawarma-chicken',
      nameAr: 'وجبة شاورما دجاج سوري مع بطاطا',
      nameEn: 'Syrian Chicken Shawarma Platter',
      descriptionAr: 'شرائح شاورما دجاج متبلة ومحمصة على السيخ، مع خبز صاج، بطاطا مقلية، كريم ثوم ومخلل لفت شامي',
      descriptionEn: 'Thinly carved spiced chicken shawarma slices with markouk bread, toum, pickles and golden fries',
      price: 48000,
      categoryId: 'cat-shawarma',
      stationId: 'st-grill',
      prepTimeMinutes: 10,
      isAvailable: true,
      sku: 'SHW-501',
      modifiers: [
        {
          id: 'mod-shawarma-opt',
          nameAr: 'إضافات الشاورما',
          nameEn: 'Shawarma Customization',
          required: false,
          multiSelect: true,
          options: [
            { id: 'opt-spicy-dip', nameAr: 'شطة حمراء حارة', nameEn: 'Spicy Chili Dip', priceDelta: 0 },
            { id: 'opt-extra-toum', nameAr: 'زيادة ثومية', nameEn: 'Extra Garlic Cream', priceDelta: 3000 },
            { id: 'opt-cheese', nameAr: 'إضافة جبنة قشقوان', nameEn: 'Add Kashkaval Cheese', priceDelta: 8000 },
          ],
        },
      ],
    },
    {
      id: 'prd-lemon-mint',
      nameAr: 'عصير ليمون ونعنع شامي طازج',
      nameEn: 'Fresh Damascus Lemonade & Mint',
      descriptionAr: 'عصير ليمون طبيعي مثلج ومخفوق مع أوراق النعناع البلدي الطازج وقليل من ماء الزهر',
      descriptionEn: 'Ice blended fresh natural lemon juice with garden mint leaves and orange blossom touch',
      price: 18000,
      categoryId: 'cat-cold-drinks',
      stationId: 'st-drinks',
      prepTimeMinutes: 4,
      isAvailable: true,
      sku: 'DRK-601',
      modifiers: [
        {
          id: 'mod-sugar',
          nameAr: 'درجة الحلاوة',
          nameEn: 'Sweetness',
          required: false,
          multiSelect: false,
          options: [
            { id: 'opt-sug-normal', nameAr: 'سكر عادي', nameEn: 'Regular Sweetness', priceDelta: 0 },
            { id: 'opt-sug-light', nameAr: 'سكر خفيف', nameEn: 'Light Sugar', priceDelta: 0 },
            { id: 'opt-sug-none', nameAr: 'بدون سكر (حامض)', nameEn: 'No Sugar (Tart)', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-cola',
      nameAr: 'مشروب غازي كولا / ميريندا',
      nameEn: 'Soft Drink (Cola / Mirinda / 7Up)',
      descriptionAr: 'عبوة زجاجية باردة مع مكعبات ثلج وشريحة ليمون',
      descriptionEn: 'Chilled soft drink served with ice cubes and fresh lemon slice',
      price: 9000,
      categoryId: 'cat-cold-drinks',
      stationId: 'st-drinks',
      prepTimeMinutes: 2,
      isAvailable: true,
      sku: 'DRK-602',
      modifiers: [
        {
          id: 'mod-drink-flavor',
          nameAr: 'نوع المشروب',
          nameEn: 'Drink Flavor',
          required: true,
          multiSelect: false,
          options: [
            { id: 'opt-coca-cola', nameAr: 'كوكا كولا', nameEn: 'Coca Cola', priceDelta: 0 },
            { id: 'opt-sprite', nameAr: 'سفن آب / سبرايت', nameEn: '7Up / Sprite', priceDelta: 0 },
            { id: 'opt-mirinda', nameAr: 'ميريندا برتقال', nameEn: 'Mirinda Orange', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-arabic-coffee',
      nameAr: 'قهوة سورية بالهيل وزهر الليمون',
      nameEn: 'Arabic Coffee with Cardamom',
      descriptionAr: 'فنجان قهوة عربية محمصة ومطحونة بالهيل تقدم بركوة نحاسية تقليدية',
      descriptionEn: 'Traditional Damascus brass-pot brewed coffee scented with green cardamom',
      price: 12000,
      categoryId: 'cat-hot-drinks',
      stationId: 'st-drinks',
      prepTimeMinutes: 5,
      isAvailable: true,
      sku: 'DRK-603',
      modifiers: [
        {
          id: 'mod-coffee-sugar',
          nameAr: 'السكر',
          nameEn: 'Coffee Sugar',
          required: false,
          multiSelect: false,
          options: [
            { id: 'opt-cof-murra', nameAr: 'سادة (مرة)', nameEn: 'No Sugar (Murra)', priceDelta: 0 },
            { id: 'opt-cof-wasat', nameAr: 'وسط', nameEn: 'Medium Sugar', priceDelta: 0 },
            { id: 'opt-cof-helwa', nameAr: 'حلوة زيادة', nameEn: 'Sweet', priceDelta: 0 },
          ],
        },
      ],
    },
    {
      id: 'prd-baklava',
      nameAr: 'صحن بقلاوة مشكلة بالفستق الحلبي',
      nameEn: 'Damascus Pistachio Baklava Plate',
      descriptionAr: 'رقائق عجين البقلاوة الهشة بالسمن الحيواني الفاخر محشوة بالفستق الحلبي الأخضر والقطر',
      descriptionEn: 'Crispy layered phyllo pastry filled with green Aleppo pistachios and floral sugar syrup',
      price: 36000,
      categoryId: 'cat-sweets',
      stationId: 'st-desserts',
      prepTimeMinutes: 4,
      isAvailable: true,
      sku: 'SWT-701',
      modifiers: [],
    },
  ],
  orders: [],
  orderEvents: [],
  printers: [
    {
      id: 'prn-main',
      name: 'طابعة المطبخ الرئيسية (Thermal 80mm)',
      ip: '192.168.1.120',
      port: 9100,
      type: 'NETWORK',
      paperWidth: '80mm',
      stationId: 'ALL',
      isActive: true,
      lastStatus: 'ONLINE',
    },
    {
      id: 'prn-grill',
      name: 'طابعة قسم المشاوي والفحم (80mm)',
      ip: '192.168.1.121',
      port: 9100,
      type: 'NETWORK',
      paperWidth: '80mm',
      stationId: 'st-grill',
      isActive: true,
      lastStatus: 'ONLINE',
    },
    {
      id: 'prn-bar',
      name: 'طابعة بار المشروبات (58mm)',
      ip: '192.168.1.122',
      port: 9100,
      type: 'NETWORK',
      paperWidth: '58mm',
      stationId: 'st-drinks',
      isActive: true,
      lastStatus: 'ONLINE',
    },
  ],
  auditLogs: [
    {
      id: 'log-1',
      userId: 'usr-admin',
      userName: 'المدير العام (أبو سليم)',
      userRole: 'ADMIN',
      action: 'SYSTEM_BOOT',
      detailsAr: 'تم تهيئة نظام مطعم بيتنا الشامي بنجاح',
      detailsEn: 'Baitna Al-Shami Restaurant system booted and initialized',
      timestamp: '2026-09-22T04:00:00.000Z',
    },
  ],
};
